=== addosso/University---Ecommerce-Project/ecommerce_2016_1610889/WebContent/files/market.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		elementFormDefault="qualified"
		targetNamespace="http://melatti.org/market"
		xmlns="http://melatti.org/market" >
  
  <xs:element name="id" type="xs:integer"/>

  <xs:element name="currency">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
	<xs:element name="toEUR" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
	<xs:element name="toDollar" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="image">
    <xs:complexType>
      <xs:attribute name="src" type="xs:string" use="optional"/>
      <xs:attribute name="alt" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="id"/>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="description" type="xs:string" minOccurs="0"/>
	<xs:element name="price" type="xs:decimal"/>
	<xs:element ref="currency"/>
	<xs:element name="available" type="xs:dateTime"/>
	<xs:element ref="image" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="show" type="xs:boolean" use="optional" default="true"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="account">
    <xs:complexType>
      <xs:attribute name="username" type="xs:string" use="required"/>
      <xs:attribute name="password" type="xs:string" use="required"/>
      <xs:attribute name="realname" type="xs:string" use="optional"/>
      <xs:attribute name="realsurname" type="xs:string" use="optional"/>
      <xs:attribute name="accountType" use="required">
	<xs:simpleType>
	  <xs:restriction base="xs:string">
	    <xs:pattern value="administrator"/>
	    <xs:pattern value="regular"/>
	  </xs:restriction>
	</xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="accounts">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="account" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="category">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="id"/>
	<xs:element ref="item" minOccurs="0" maxOccurs="unbounded"/>
	<xs:element ref="image" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="categories">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="category" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="market">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="accounts" minOccurs="0" maxOccurs="1"/>
	<xs:element ref="categories" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== addosso/University---Ecommerce-Project/ecommerce_2016_1610889/WebContent/files/market.xml
<?xml version="1.0"?>
<market xmlns="http://melatti.org/market"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="market.xsd">
  <accounts>
    <account username="root" password="12345" accountType="administrator"/>
    <account username="antonio" realname="Antonio" realsurname="La Trippa" password="12345" accountType="regular"/>
  </accounts>

  <categories>
    <category name="Books">
      <id>1</id>
      <item show="true">
	<id>1</id>
	<title>La Divina Commedia</title>
	<description>A rather complicated fantasy tale by D. Alighieri (in Italian)</description>
	<price>10</price>
	<currency>
	  <name>EUR</name>
	  <toEUR>1</toEUR>
	  <toDollar>1.1031</toDollar>
	</currency>
	<available>2016-01-01T00:00:00</available>
	<image src="images/divina-commedia-ed-rossa.jpg"/>
      </item>
      <item>
	<id>2</id>
	<title>Paradise Lost</title>
	<description>A rather complicated fantasy tale by J. Milton (in ancient English)</description>
	<price>20</price>
	<currency>
	  <name>Pounds</name>
	  <toEUR>1.28988306</toEUR>
	</currency>
	<available>2016-01-01T00:00:00</available>
	<image src="images/paradise_lost.jpg"/>
      </item>
      <image src="images/books.jpeg"/>
    </category>

    <category name="For your home">
      <id>2</id>
      <item>
	<id>1</id>
	<title>Mirror</title>
	<description>A precious mirror for your bathroom</description>
	<price>100</price>
	<currency>
	  <name>EUR</name>
	  <toEUR>1</toEUR>
	  <toDollar>1.1031</toDollar>
	</currency>
	<available>2016-01-01T00:00:00</available>
      </item>
      <item>
	<id>2</id>
	<title>Desk</title>
	<description>A marvellous desk in wood</description>
	<price>1000</price>
	<currency>
	  <name>Pounds</name>
	  <toEUR>1.28988306</toEUR>
	</currency>
	<available>2016-01-01T00:00:00</available>
	<image src="images/scrivania.jpeg"/>
      </item>
    </category>

    <category name="Beauty">
      <id>3</id>
      <item>
	<id>1</id>
	<title>Eau de Chanel n. 5</title>
	<description>A description is not needed</description>
	<price>100</price>
	<currency>
	  <name>EUR</name>
	  <toEUR>1</toEUR>
	  <toDollar>1.1031</toDollar>
	</currency>
	<available>2016-01-01T00:00:00</available>
	<image src="images/chanel.jpeg"/>
      </item>
      <item>
	<id>2</id>
	<title>Make-up</title>
	<description>Complete make-up in one box</description>
	<price>100</price>
	<currency>
	  <name>Pounds</name>
	  <toEUR>1.28988306</toEUR>
	</currency>
	<available>2016-01-01T00:00:00</available>
      </item>
    </category>
  </categories>
</market>
